import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service | Plot Twists',
  description: 'Terms of service for Plot Twists — the improv comedy game.',
}

export default function TermsOfServicePage() {
  return (
    <main className="min-h-dvh py-12 px-4" style={{ background: 'var(--color-void, #08070b)', color: '#f0ece4' }}>
      <div className="max-w-2xl mx-auto">
        <Link
          href="/"
          className="inline-flex items-center gap-1 text-sm mb-8 transition-colors"
          style={{ color: 'var(--color-accent)' }}
        >
          <span>&larr;</span> Back to Plot Twists
        </Link>

        <h1 className="text-3xl font-bold mb-2" style={{ color: '#f0ece4', fontFamily: 'var(--font-serif)' }}>
          Terms of Service
        </h1>
        <p className="text-sm mb-8" style={{ color: 'rgba(240,236,228,0.4)' }}>
          Last updated: February 12, 2026
        </p>

        <div className="space-y-6 text-sm leading-relaxed" style={{ color: 'rgba(240,236,228,0.7)' }}>
          <section>
            <h2 className="text-lg font-semibold mb-2" style={{ color: '#f0ece4', fontFamily: 'var(--font-serif)' }}>1. Acceptance of Terms</h2>
            <p>
              By accessing or using Plot Twists (the &ldquo;Service&rdquo;), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2" style={{ color: '#f0ece4', fontFamily: 'var(--font-serif)' }}>2. Description of Service</h2>
            <p>
              Plot Twists is an improv comedy game where players draw cards, AI generates comedy scripts, and players
              perform them live. The Service is available via web browser and iOS app.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2" style={{ color: '#f0ece4', fontFamily: 'var(--font-serif)' }}>3. Accounts</h2>
            <p>
              You may use the Service as a guest or create an account using email. You are responsible for
              maintaining the security of your account and for all activity that occurs under it.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2" style={{ color: '#f0ece4', fontFamily: 'var(--font-serif)' }}>4. Credits &amp; Purchases</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>The Service uses a credit system. Each script generation consumes one credit.</li>
              <li>Free users receive a limited number of credits per week that reset automatically.</li>
              <li>Additional credits can be purchased through Stripe (web) or Apple In-App Purchase (iOS).</li>
              <li>Purchased credits (&ldquo;banked credits&rdquo;) do not expire and are non-transferable.</li>
              <li>All purchases are final. Refunds are handled in accordance with the applicable platform&apos;s
                refund policy (Stripe or Apple App Store).</li>
              <li>Credits have no cash value and cannot be exchanged for currency.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2" style={{ color: '#f0ece4', fontFamily: 'var(--font-serif)' }}>5. AI-Generated Content</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>Scripts are generated by AI based on card selections and game settings.</li>
              <li>AI-generated content is intended for entertainment purposes only.</li>
              <li>We do not guarantee the quality, accuracy, or appropriateness of AI-generated scripts.</li>
              <li>Content filters are applied, but AI may occasionally produce unexpected results.</li>
              <li>You may share generated scripts, but you may not claim AI-generated content as solely your own
                original work.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2" style={{ color: '#f0ece4', fontFamily: 'var(--font-serif)' }}>6. User-Generated Card Packs</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>Users may create and share custom card packs through the Service.</li>
              <li>You retain ownership of card pack content you create.</li>
              <li>By publishing a card pack, you grant us a non-exclusive license to display and distribute it
                within the Service.</li>
              <li>Card packs must not contain hateful, illegal, or sexually explicit content.</li>
              <li>We reserve the right to remove card packs that violate these terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2" style={{ color: '#f0ece4', fontFamily: 'var(--font-serif)' }}>7. Acceptable Use</h2>
            <p className="mb-2">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Use the Service for any unlawful purpose.</li>
              <li>Attempt to gain unauthorized access to the Service or its systems.</li>
              <li>Interfere with or disrupt the Service or servers.</li>
              <li>Use automated means (bots, scrapers) to access the Service.</li>
              <li>Harass, abuse, or harm other users during games.</li>
              <li>Exploit bugs or vulnerabilities instead of reporting them.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2" style={{ color: '#f0ece4', fontFamily: 'var(--font-serif)' }}>8. Account Termination</h2>
            <p>
              You may delete your account at any time from Account Settings. We may suspend or terminate your account
              if you violate these terms. Upon deletion, your profile, statistics, game history, and linked payment
              data will be permanently removed.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2" style={{ color: '#f0ece4', fontFamily: 'var(--font-serif)' }}>9. Disclaimers</h2>
            <p>
              The Service is provided &ldquo;as is&rdquo; without warranties of any kind, either express or implied. We do not
              warrant that the Service will be uninterrupted, error-free, or that any defects will be corrected.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2" style={{ color: '#f0ece4', fontFamily: 'var(--font-serif)' }}>10. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Plot Twists shall not be liable for any indirect, incidental,
              special, or consequential damages arising from your use of the Service, including loss of data, credits,
              or profits.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2" style={{ color: '#f0ece4', fontFamily: 'var(--font-serif)' }}>11. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after changes constitutes
              acceptance of the new terms. We will notify you of significant changes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2" style={{ color: '#f0ece4', fontFamily: 'var(--font-serif)' }}>12. Contact</h2>
            <p>
              For questions about these Terms, contact us at:
            </p>
            <p className="mt-2 font-medium" style={{ color: '#f0ece4' }}>
              support@plot-twists.com
            </p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t text-center text-xs" style={{ borderColor: 'rgba(240,236,228,0.1)', color: 'rgba(240,236,228,0.3)' }}>
          <Link href="/privacy" className="underline" style={{ color: 'rgba(240,236,228,0.5)' }}>Privacy Policy</Link>
          {' '}&middot;{' '}
          <Link href="/" style={{ color: 'rgba(240,236,228,0.5)' }}>Plot Twists</Link>
        </div>
      </div>
    </main>
  )
}
