/**
 * IP layer 3 — protected-term list for output screening.
 *
 * GENERATED 2026-07-29 from `lib/content.ts` **before** the Layer 1 archetype
 * rewrite, deliberately. The rewrite deletes these names from the catalog, and
 * once it lands there is no longer any record in the repo of what the model was
 * previously being taught to produce. This file is that record.
 *
 * Screening is for what the MODEL volunteers, which is a different problem from
 * what a player can submit (layer 2 closed that). A model trained on the open
 * internet will offer "Darth Vader" for a wheezing space tyrant whether or not
 * the prompt asked.
 *
 * ── Precision over recall, on purpose ────────────────────────────────────────
 * Terms that are also ordinary English are EXCLUDED, not included: "Friends",
 * "The Office", "The Boys", "Joy", "Anger", "Eleven", "Penny", "Cars", "Soul",
 * "Alien", "Frozen", "Donkey", "Cheers", "Monk". A screen that fires on
 * "the boys are back" is a screen someone disables inside a week, and a
 * disabled screen catches nothing at all. Single words are kept only at 6+
 * characters and only when distinctive.
 *
 * The cost of that choice, stated plainly: this catches NAMED entities only. It
 * cannot catch "a wheezing tyrant in black armour who is secretly your father",
 * which is the same exposure with the noun removed. That needs a semantic pass
 * — see AUDIT.md → IP layer 3, "what this does not catch".
 */

/**
 * Franchise characters and titles. Redacted from prose, logged in speakers.
 *
 * REMOVED after testing, do not re-add:
 *   'Die Hard'  — fires on "old habits die hard", which is just English.
 *   'Rapunzel'  — a Brothers Grimm character, public domain. The specific
 *                 animated-film DESIGN is protected; the name is not.
 * Both were caught by screening the repo's own source with this list. See the
 * false-positive cases in contentScreen.service.test.ts.
 */
export const PROTECTED_TERMS: string[] = [
  'Alex the Lion',
  'Alice in Wonderland',
  'American Psycho',
  'Amy Santiago',
  'Andy Dwyer',
  'Ant-Man',
  'April Ludgate',
  'Arthur Shelby',
  'Back to the Future',
  'Barney Stinson',
  'Bart Simpson',
  'Beauty and the Beast',
  'Black Panther',
  'Black Widow',
  'BoJack Horseman',
  'Breaking Bad',
  'Brooklyn Nine-Nine',
  'Bruno Madrigal',
  'Buzz Lightyear',
  'Captain America',
  'Captain Holt',
  'Captain Kirk',
  'Carmela Soprano',
  'Chandler Bing',
  'Charles Boyle',
  'Charlie Kelly',
  'Charlie and the Chocolate Factory',
  'Cher Horowitz',
  'Chidi Anagonye',
  'Christopher Moltisanti',
  'Claire Underwood',
  'Clarice Starling',
  'Cosmo Kramer',
  'DC Comics',
  'Darth Vader',
  'Debra Morgan',
  'Dee Reynolds',
  'Dennis Reynolds',
  'Dexter Morgan',
  'Doc Brown',
  'Doctor Strange',
  'Doctor Who',
  'Don Draper',
  'Dorothy Gale',
  'Drax the Destroyer',
  'Dwight Schrute',
  'Edna Mode',
  'Edward Scissorhands',
  'Elaine Benes',
  'Elastigirl',
  'Eleanor Shellstrop',
  'Elle Woods',
  'Ellen Ripley',
  'Ethan Hunt',
  'Eve Polastri',
  'Ferris Bueller',
  'Ferris Bueller\'s Day Off',
  'Finding Nemo',
  'Flynn Rider',
  'Forrest Gump',
  'Frank Reynolds',
  'Frank Underwood',
  'Frasier',
  'Frasier Crane',
  'Futurama',
  'George Costanza',
  'Ghostbusters',
  'Gina Linetti',
  'Glinda the Good Witch',
  'Guardians of the Galaxy',
  'Gus Fring',
  'Han Solo',
  'Hannibal Lecter',
  'Harley Quinn',
  'Harry Potter',
  'Hermione Granger',
  'Homer Simpson',
  'House of Cards',
  'How I Met Your Mother',
  'How to Train Your Dragon',
  'Indiana Jones',
  'Iron Man',
  'It\'s Always Sunny',
  'Jack Bauer',
  'Jake Peralta',
  'James Bond',
  'Jason Mendoza',
  'Jean-Luc Picard',
  'Jerry Seinfeld',
  'Jesse Pinkman',
  'Jessica Fletcher',
  'Jim Halpert',
  'Jimmy McNulty',
  'Joan Holloway',
  'Joey Tribbiani',
  'John McClane',
  'John Wick',
  'Jurassic Park',
  'Karate Kid',
  'Kendall Roy',
  'Kevin McCallister',
  'Killing Eve',
  'King Julien',
  'Kung Fu Panda',
  'Kylo Ren',
  'Lana Kane',
  'Legally Blonde',
  'Leonard Hofstadter',
  'Leslie Knope',
  'Lieutenant Dan',
  'Lightning McQueen',
  'Lily Aldrin',
  'Logan Roy',
  'Lord of the Rings',
  'Lucifer Morningstar',
  'Luke Skywalker',
  'Madagascar',
  'Marge Simpson',
  'Marshall Eriksen',
  'Marty Byrde',
  'Marty Hart',
  'Marty McFly',
  'Mary Poppins',
  'Master Shifu',
  'McGonagall',
  'Men in Black',
  'Michael',
  'Michael Corleone',
  'Michael Scott',
  'Mike Ehrmantraut',
  'Mike Wazowski',
  'Mirabel Madrigal',
  'Mission: Impossible',
  'Monica Geller',
  'Monsters Inc.',
  'Morty Smith',
  'Mr. Bean',
  'Mr. Incredible',
  'Mr. Potato Head',
  'Mr. Spock',
  'Murder She Wrote',
  'Nancy Drew',
  'Niles Crane',
  'Obi-Wan Kenobi',
  'Omar Little',
  'Pam Beesly',
  'Pam Poovey',
  'Parks and Recreation',
  'Patrick Bateman',
  'Patrick Star',
  'Paulie Walnuts',
  'Peaky Blinders',
  'Peggy Olson',
  'Peter Pan',
  'Phoebe Buffay',
  'Polly Gray',
  'Princess Carolyn',
  'Princess Jasmine',
  'Princess Leia',
  'Princess Peach',
  'Puss in Boots',
  'Rachel Green',
  'Ratatouille',
  'Rebecca Welton',
  'Rick Sanchez',
  'Rick and Morty',
  'Rocket Raccoon',
  'Rocky Balboa',
  'Roger Sterling',
  'Roman Roy',
  'Ron Swanson',
  'Ron Weasley',
  'Rosa Diaz',
  'Ross Geller',
  'Roy Kent',
  'Rust Cohle',
  'Samwise Gamgee',
  'Sarah Connor',
  'Saul Goodman',
  'Scarlet Witch',
  'Scooby-Doo',
  'Seinfeld',
  'Sesame Street',
  'Shawn Spencer',
  'Sheldon Cooper',
  'Sherlock Holmes',
  'Shiv Roy',
  'Silence of the Lambs',
  'Spider-Man',
  'SpongeBob SquarePants',
  'Star Trek',
  'Star Wars',
  'Star-Lord',
  'Sterling Archer',
  'Steve Harrington',
  'Stranger Things',
  'Stringer Bell',
  'Summer Smith',
  'Super Mario',
  'Tahani Al-Jamil',
  'Ted Lasso',
  'Ted Mosby',
  'Terminator',
  'The Big Bang Theory',
  'The Cowardly Lion',
  'The Godfather',
  'The Good Place',
  'The Hulk',
  'The Incredibles',
  'The Karate Kid',
  'The Lion King',
  'The Little Mermaid',
  'The Scarecrow',
  'The Shining',
  'The Simpsons',
  'The Sopranos',
  'The Terminator',
  'The Tin Man',
  'The Wizard of Oz',
  'Thor: Ragnarok',
  'Todd Chavez',
  'Tommy Shelby',
  'Tony Soprano',
  'Toy Story',
  'True Detective',
  'Tyler Durden',
  'WALL-E',
  'Walter White',
  'Wendy Byrde',
  'Willy Wonka',
  'Winnie the Pooh',
  'Wonder Woman',
  'Yellowstone',
]

/**
 * Real, living, commercially active people. Right of publicity is state law,
 * needs no registration, and has no fair-use safe harbour for commercial use —
 * a separate and in some ways worse exposure than the franchise list above.
 *
 * This list cannot be complete; a model can name anyone. It covers names the
 * catalog itself used to carry plus the most likely volunteers. General
 * detection needs the semantic pass.
 */
export const REAL_PEOPLE: string[] = [
  'Jerry Seinfeld',
  // Was named FOUR TIMES in the system prompt as a voice exemplar ("EVERY line
  // should sound exactly like Gordon Ramsay"). Found by screening the prompt
  // files with this module's own matcher, not by the Chunk 4 done-criterion
  // grep — whose fixed term list never contained him. A fixed grep only finds
  // the terms you already thought of.
  'Gordon Ramsay',
  'Taylor Swift',
  'Elon Musk',
  'Tom Cruise',
  'Beyonce',
  'Beyoncé',
  'Kanye West',
  'Oprah Winfrey',
  'Dwayne Johnson',
  'Keanu Reeves',
  'Ryan Reynolds',
  'Kim Kardashian',
  'Donald Trump',
  'Barack Obama',
  'Joe Rogan',
  'MrBeast',
  'Bill Gates',
  'Jeff Bezos',
  'Mark Zuckerberg',
]
