import type { Script } from './types'

export function formatScriptAsText(script: Script): string {
  let output = ''

  // Title
  output += '=' .repeat(60) + '\n'
  output += script.title.toUpperCase() + '\n'
  output += '=' .repeat(60) + '\n\n'

  // Synopsis
  output += script.synopsis + '\n\n'
  output += '-'.repeat(60) + '\n\n'

  // Lines
  script.lines.forEach((line, index) => {
    // Speaker name (centered-ish)
    output += `${line.speaker.toUpperCase()}\n`

    // Mood indicator
    output += `(${line.mood})\n`

    // Dialogue
    output += `     ${line.text}\n\n`

    // Add separator between lines
    if (index < script.lines.length - 1) {
      output += '\n'
    }
  })

  // Footer
  output += '\n' + '-'.repeat(60) + '\n'
  output += 'Generated by Plot Twists\n'
  output += 'https://plot-twists.com\n'
  output += '=' .repeat(60) + '\n'

  return output
}

export function downloadScript(script: Script) {
  const text = formatScriptAsText(script)
  const blob = new Blob([text], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')

  // Create filename from script title
  const filename = `${script.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt`

  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export async function copyScriptToClipboard(script: Script): Promise<boolean> {
  try {
    const text = formatScriptAsText(script)
    await navigator.clipboard.writeText(text)
    return true
  } catch (error) {
    console.error('Failed to copy script:', error)
    return false
  }
}

export function shareScript(script: Script): { title: string; text: string; url?: string } {
  return {
    title: script.title,
    text: `Check out this hilarious improv script from Plot Twists!\n\n"${script.title}"\n${script.synopsis}`,
    url: typeof window !== 'undefined' ? window.location.origin : undefined
  }
}

export function getCharactersInScene(script: Script): string[] {
  // Extract unique characters in order of first appearance
  const seen = new Set<string>()
  const characters: string[] = []

  script.lines.forEach(line => {
    if (!seen.has(line.speaker)) {
      seen.add(line.speaker)
      characters.push(line.speaker)
    }
  })

  return characters
}
