/**
 * Mock Anthropic Messages API for the realtime harness.
 *
 * Speaks enough of the streaming Messages protocol that the REAL
 * scriptGeneration.service.ts code path runs unmodified — streaming,
 * progress milestones, extractJSON, and Zod validation all execute.
 *
 * Point the SDK at it with ANTHROPIC_BASE_URL=http://127.0.0.1:<port>
 *
 * Fault modes (set via MOCK_MODE env or ?mode= on the request):
 *   ok        — well-formed script (default)
 *   slow      — well-formed, but streamed over MOCK_DELAY_MS
 *   malformed — returns prose with no JSON at all
 *   truncated — returns JSON cut off mid-array
 *   error     — returns HTTP 529 overloaded_error
 *   hang      — accepts the request and never responds
 */

import { createServer, type IncomingMessage, type ServerResponse } from 'http'

export interface MockStats {
  requests: number
  /** Per-request log. Lets a scenario count ONE KIND of call — a round makes several
   * Anthropic requests (script, plot-twist pre-generation, director's review), so a bare
   * `requests` delta cannot answer "how many SCRIPTS were generated". */
  log: Array<{ maxTokens: number; systemPrompt: string; userMessage: string }>
  lastSystemPrompt: string
  lastUserMessage: string
  lastModel: string
  lastMaxTokens: number
  promptChars: number
}

export const stats: MockStats = {
  requests: 0,
  log: [],
  lastSystemPrompt: '',
  lastUserMessage: '',
  lastModel: '',
  lastMaxTokens: 0,
  promptChars: 0,
}

function buildScript(lineCount: number): string {
  const speakers = ['PLAYER ONE', 'PLAYER TWO', 'PLAYER THREE']
  const lines = Array.from({ length: lineCount }, (_, i) => ({
    speaker: speakers[i % speakers.length],
    text: `Harness line ${i + 1}. This is deterministic filler dialogue used for load testing.`,
    mood: 'neutral',
  }))
  return JSON.stringify({
    title: 'The Harness Test',
    synopsis: 'A deterministic scene generated by the audit harness.',
    lines,
  })
}

function sse(res: ServerResponse, event: string, data: unknown) {
  res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`)
}

async function streamText(res: ServerResponse, text: string, delayMs: number) {
  // chunk into ~40-char deltas, like a real token stream
  const chunkSize = 40
  for (let i = 0; i < text.length; i += chunkSize) {
    sse(res, 'content_block_delta', {
      type: 'content_block_delta',
      index: 0,
      delta: { type: 'text_delta', text: text.slice(i, i + chunkSize) },
    })
    if (delayMs > 0) await new Promise(r => setTimeout(r, delayMs))
  }
}

export function startMockAnthropic(port: number): Promise<{ close: () => Promise<void>; port: number }> {
  const server = createServer(async (req: IncomingMessage, res: ServerResponse) => {
    if (!req.url?.includes('/v1/messages')) {
      res.writeHead(404).end()
      return
    }

    let body = ''
    for await (const chunk of req) body += chunk

    let parsed: Record<string, unknown> = {}
    try { parsed = JSON.parse(body) } catch { /* ignore */ }

    stats.requests++
    stats.lastModel = String(parsed.model ?? '')
    stats.lastMaxTokens = Number(parsed.max_tokens ?? 0)
    stats.lastSystemPrompt = String(parsed.system ?? '')
    const msgs = (parsed.messages as Array<{ content: string }>) ?? []
    stats.lastUserMessage = msgs.map(m => m.content).join('\n')
    stats.promptChars = stats.lastSystemPrompt.length + stats.lastUserMessage.length
    stats.log.push({ maxTokens: stats.lastMaxTokens, systemPrompt: stats.lastSystemPrompt, userMessage: stats.lastUserMessage })

    const mode = process.env.MOCK_MODE || 'ok'
    const delayMs = Number(process.env.MOCK_DELAY_MS || 0)

    if (mode === 'hang') return // never respond

    if (mode === 'error') {
      res.writeHead(529, { 'content-type': 'application/json' })
      res.end(JSON.stringify({ type: 'error', error: { type: 'overloaded_error', message: 'Overloaded' } }))
      return
    }

    let payload: string
    if (mode === 'malformed') {
      payload = "I'd be happy to help! However, I can't produce that scene."
    } else if (mode === 'truncated') {
      payload = buildScript(35).slice(0, 400)
    } else {
      payload = buildScript(35)
    }

    const inputTokens = Math.ceil(stats.promptChars / 4)
    const outputTokens = Math.ceil(payload.length / 4)

    // Non-streaming callers (audience.service, directorsReview.service use
    // messages.create) get a plain JSON message back.
    if (!parsed.stream) {
      res.writeHead(200, { 'content-type': 'application/json' })
      res.end(JSON.stringify({
        id: 'msg_harness',
        type: 'message',
        role: 'assistant',
        model: stats.lastModel,
        content: [{ type: 'text', text: payload }],
        stop_reason: 'end_turn',
        stop_sequence: null,
        usage: { input_tokens: inputTokens, output_tokens: outputTokens },
      }))
      return
    }

    res.writeHead(200, {
      'content-type': 'text/event-stream',
      'cache-control': 'no-cache',
      connection: 'keep-alive',
    })

    sse(res, 'message_start', {
      type: 'message_start',
      message: {
        id: 'msg_harness',
        type: 'message',
        role: 'assistant',
        model: stats.lastModel,
        content: [],
        stop_reason: null,
        stop_sequence: null,
        usage: { input_tokens: inputTokens, output_tokens: 0 },
      },
    })
    sse(res, 'content_block_start', {
      type: 'content_block_start',
      index: 0,
      content_block: { type: 'text', text: '' },
    })

    await streamText(res, payload, mode === 'slow' ? Math.max(delayMs, 1) : 0)

    sse(res, 'content_block_stop', { type: 'content_block_stop', index: 0 })
    sse(res, 'message_delta', {
      type: 'message_delta',
      delta: { stop_reason: 'end_turn', stop_sequence: null },
      usage: { output_tokens: outputTokens },
    })
    sse(res, 'message_stop', { type: 'message_stop' })
    res.end()
  })

  return new Promise(resolve => {
    server.listen(port, '127.0.0.1', () => {
      resolve({
        port,
        close: () => new Promise<void>(r => server.close(() => r())),
      })
    })
  })
}

if (process.argv[1]?.includes('mock-anthropic')) {
  const port = Number(process.env.MOCK_PORT || 8788)
  startMockAnthropic(port).then(() => {
    console.log(`[mock-anthropic] listening on http://127.0.0.1:${port} mode=${process.env.MOCK_MODE || 'ok'}`)
  })
}
